// Mock data — used when server is not connected
// When server is connected, API calls replace these

export const CATEGORIES = [
  { id: "electronics", name: "Electronics", icon: "📱", count: 1240, color: "#3B82F6" },
  { id: "fashion", name: "Fashion", icon: "👗", count: 890, color: "#EC4899" },
  { id: "beauty", name: "Beauty", icon: "💄", count: 560, color: "#F59E0B" },
  { id: "home-kitchen", name: "Home & Kitchen", icon: "🏠", count: 720, color: "#10B981" },
  { id: "gaming", name: "Gaming", icon: "🎮", count: 430, color: "#8B5CF6" },
  { id: "phones", name: "Phones & Accessories", icon: "📲", count: 980, color: "#EF4444" },
  { id: "sports", name: "Sports & Fitness", icon: "💪", count: 340, color: "#F97316" },
  { id: "books", name: "Books & Media", icon: "📚", count: 230, color: "#6366F1" },
];

export const PRODUCTS = [
  {
    id: "p001",
    name: "Sony WH-1000XM5 Wireless Headphones",
    category: "electronics",
    categoryName: "Electronics",
    price: 185000,
    originalPrice: 245000,
    rating: 4.8,
    reviewCount: 2847,
    stock: 23,
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: true,
    description: "Industry-leading noise cancellation with 30-hour battery life. Premium sound quality with LDAC support.",
    specs: { "Driver Size": "30mm", "Battery": "30 hours", "Connectivity": "Bluetooth 5.2", "Weight": "250g" },
    brand: "Sony",
    tags: ["headphones", "wireless", "noise-cancelling"],
  },
  {
    id: "p002",
    name: "Apple iPhone 15 Pro Max",
    category: "phones",
    categoryName: "Phones",
    price: 899000,
    originalPrice: 999000,
    rating: 4.9,
    reviewCount: 5621,
    stock: 8,
    images: [
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600&q=80",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80",
    ],
    badge: "hot",
    isNew: true,
    isBestSeller: true,
    description: "A17 Pro chip, titanium design, and the most advanced iPhone camera system ever.",
    specs: { "Chip": "A17 Pro", "Storage": "256GB", "Display": "6.7\" Super Retina XDR", "Camera": "48MP" },
    brand: "Apple",
    tags: ["iphone", "smartphone", "apple"],
  },
  {
    id: "p003",
    name: "Samsung 55\" QLED 4K Smart TV",
    category: "electronics",
    categoryName: "Electronics",
    price: 420000,
    originalPrice: 580000,
    rating: 4.7,
    reviewCount: 1923,
    stock: 15,
    images: [
      "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&q=80",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: true,
    description: "Quantum Dot technology with 100% Color Volume. Alexa and Google Assistant built-in.",
    specs: { "Display": "55\" QLED 4K", "HDR": "HDR10+", "Refresh Rate": "120Hz", "Smart TV": "Tizen OS" },
    brand: "Samsung",
    tags: ["tv", "smart-tv", "qled"],
  },
  {
    id: "p004",
    name: "Nike Air Jordan 1 Retro High OG",
    category: "fashion",
    categoryName: "Fashion",
    price: 95000,
    originalPrice: 120000,
    rating: 4.9,
    reviewCount: 8934,
    stock: 34,
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    ],
    badge: "hot",
    isNew: false,
    isBestSeller: true,
    description: "The iconic Air Jordan 1 in premium leather with original colorway.",
    specs: { "Material": "Premium Leather", "Sole": "Air-Sole Unit", "Closure": "Lace-up", "Fit": "True to size" },
    brand: "Nike",
    tags: ["sneakers", "jordan", "nike"],
  },
  {
    id: "p005",
    name: "MacBook Pro 14\" M3 Pro",
    category: "electronics",
    categoryName: "Electronics",
    price: 1450000,
    originalPrice: 1600000,
    rating: 4.9,
    reviewCount: 3412,
    stock: 12,
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80",
    ],
    badge: "new",
    isNew: true,
    isBestSeller: false,
    description: "M3 Pro chip delivers exceptional performance for demanding workflows.",
    specs: { "Chip": "M3 Pro", "RAM": "18GB", "Storage": "512GB SSD", "Display": "14.2\" Liquid Retina XDR" },
    brand: "Apple",
    tags: ["laptop", "macbook", "apple"],
  },
  {
    id: "p006",
    name: "Fenty Beauty Pro Filt'r Foundation",
    category: "beauty",
    categoryName: "Beauty",
    price: 18500,
    originalPrice: 22000,
    rating: 4.6,
    reviewCount: 12043,
    stock: 89,
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: true,
    description: "Full-coverage, matte foundation in 50 shades. Long-wear formula.",
    specs: { "Coverage": "Full", "Finish": "Matte", "SPF": "SPF 15", "Shades": "50 shades" },
    brand: "Fenty Beauty",
    tags: ["foundation", "makeup", "beauty"],
  },
  {
    id: "p007",
    name: "PlayStation 5 Console",
    category: "gaming",
    categoryName: "Gaming",
    price: 450000,
    originalPrice: 500000,
    rating: 4.8,
    reviewCount: 7823,
    stock: 5,
    images: [
      "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=600&q=80",
    ],
    badge: "hot",
    isNew: false,
    isBestSeller: true,
    description: "Experience lightning-fast loading with an ultra-high-speed SSD.",
    specs: { "CPU": "AMD Zen 2 8-core", "GPU": "10.3 TFLOPS RDNA 2", "Storage": "825GB SSD", "Resolution": "8K" },
    brand: "Sony",
    tags: ["gaming", "console", "ps5"],
  },
  {
    id: "p008",
    name: "Dyson V15 Detect Vacuum Cleaner",
    category: "home-kitchen",
    categoryName: "Home & Kitchen",
    price: 285000,
    originalPrice: 340000,
    rating: 4.7,
    reviewCount: 2156,
    stock: 28,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: false,
    description: "Laser detects microscopic dust. Automatically adapts suction power.",
    specs: { "Suction": "240 AW", "Battery": "60 min", "Bin Capacity": "0.77L", "Weight": "3.1kg" },
    brand: "Dyson",
    tags: ["vacuum", "cordless", "dyson"],
  },
  {
    id: "p009",
    name: "Adidas Ultraboost 23 Running Shoes",
    category: "fashion",
    categoryName: "Fashion",
    price: 75000,
    originalPrice: 95000,
    rating: 4.7,
    reviewCount: 4521,
    stock: 42,
    images: [
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: false,
    description: "BOOST midsole delivers incredible energy return. PRIMEKNIT upper for a second-skin fit.",
    specs: { "Upper": "Primeknit+", "Midsole": "Boost", "Outsole": "Continental Rubber", "Drop": "10mm" },
    brand: "Adidas",
    tags: ["shoes", "running", "adidas"],
  },
  {
    id: "p010",
    name: "iPad Pro 12.9\" M2 Wi-Fi 256GB",
    category: "electronics",
    categoryName: "Electronics",
    price: 780000,
    originalPrice: 850000,
    rating: 4.8,
    reviewCount: 4108,
    stock: 19,
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80",
    ],
    badge: "new",
    isNew: true,
    isBestSeller: true,
    description: "The most advanced iPad, featuring M2 chip and Liquid Retina XDR display.",
    specs: { "Chip": "M2", "Display": "12.9\" Liquid Retina XDR", "Storage": "256GB", "Camera": "12MP Wide" },
    brand: "Apple",
    tags: ["ipad", "tablet", "apple"],
  },
  {
    id: "p011",
    name: "Charlotte Tilbury Pillow Talk Lipstick",
    category: "beauty",
    categoryName: "Beauty",
    price: 12500,
    originalPrice: 15000,
    rating: 4.9,
    reviewCount: 18234,
    stock: 156,
    images: [
      "https://images.unsplash.com/photo-1586495777744-4e6232bf2d8b?w=600&q=80",
    ],
    badge: "hot",
    isNew: false,
    isBestSeller: true,
    description: "The iconic Pillow Talk lipstick. Medium-coverage, satin-finish nude pink.",
    specs: { "Finish": "Satin", "Formula": "Long-wear", "Coverage": "Medium", "Cruelty-free": "Yes" },
    brand: "Charlotte Tilbury",
    tags: ["lipstick", "makeup", "beauty"],
  },
  {
    id: "p012",
    name: "LG C3 65\" OLED evo Smart TV",
    category: "electronics",
    categoryName: "Electronics",
    price: 890000,
    originalPrice: 1100000,
    rating: 4.9,
    reviewCount: 3234,
    stock: 7,
    images: [
      "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&q=80",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: true,
    description: "Brightest OLED evo ever. Perfect blacks, Dolby Vision & Atmos, 120Hz gaming.",
    specs: { "Panel": "OLED evo", "Size": "65\"", "Resolution": "4K", "Refresh Rate": "120Hz" },
    brand: "LG",
    tags: ["oled", "tv", "lg"],
  },
];

export const FLASH_SALES = PRODUCTS.filter((p) => p.badge === "sale").slice(0, 6);
export const BEST_SELLERS = PRODUCTS.filter((p) => p.isBestSeller).slice(0, 8);
export const NEW_ARRIVALS = PRODUCTS.filter((p) => p.isNew).slice(0, 8);

export const BRANDS = [
  { id: "apple", name: "Apple", logo: "🍎" },
  { id: "samsung", name: "Samsung", logo: "📱" },
  { id: "sony", name: "Sony", logo: "🎵" },
  { id: "nike", name: "Nike", logo: "✓" },
  { id: "adidas", name: "Adidas", logo: "⭐" },
  { id: "dyson", name: "Dyson", logo: "💨" },
  { id: "lg", name: "LG", logo: "📺" },
  { id: "fenty", name: "Fenty Beauty", logo: "💄" },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Adaeze Okafor",
    location: "Lagos, Nigeria",
    rating: 5,
    comment: "NexMart has completely changed how I shop. The product quality is exceptional and delivery was faster than expected. Highly recommend!",
    avatar: "AO",
    verified: true,
    date: "2 days ago",
  },
  {
    id: 2,
    name: "Emeka Nwosu",
    location: "Abuja, Nigeria",
    rating: 5,
    comment: "Best online marketplace in Nigeria. Got my MacBook Pro delivered in 2 days. The packaging was perfect and everything was authentic.",
    avatar: "EN",
    verified: true,
    date: "1 week ago",
  },
  {
    id: 3,
    name: "Fatima Al-Hassan",
    location: "Kano, Nigeria",
    rating: 5,
    comment: "The return process was seamless when I needed to exchange a size. Customer support was extremely helpful and responsive.",
    avatar: "FA",
    verified: true,
    date: "2 weeks ago",
  },
  {
    id: 4,
    name: "Chukwudi Eze",
    location: "Port Harcourt",
    rating: 4,
    comment: "Great selection of electronics. Prices are competitive and the flash sales are amazing. Found the PS5 at a great price!",
    avatar: "CE",
    verified: true,
    date: "3 weeks ago",
  },
];
