// ─── Categories ───────────────────────────────────────────────────────────────
export const CATEGORIES = [
  { id: "electronics",  name: "Electronics",        icon: "📱", count: 1240, color: "#3B82F6" },
  { id: "fashion",      name: "Fashion",             icon: "👗", count: 890,  color: "#EC4899" },
  { id: "beauty",       name: "Beauty",              icon: "💄", count: 560,  color: "#F59E0B" },
  { id: "home-kitchen", name: "Home & Kitchen",      icon: "🏠", count: 720,  color: "#10B981" },
  { id: "gaming",       name: "Gaming",              icon: "🎮", count: 430,  color: "#8B5CF6" },
  { id: "phones",       name: "Phones & Accessories",icon: "📲", count: 980,  color: "#EF4444" },
  { id: "sports",       name: "Sports & Fitness",    icon: "💪", count: 340,  color: "#F97316" },
  { id: "books",        name: "Books & Media",       icon: "📚", count: 230,  color: "#6366F1" },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const PRODUCTS = [

  // ── ELECTRONICS (12 products) ─────────────────────────────────────────────
  {
    id: "p001",
    name: "Sony WH-1000XM5 Wireless Headphones",
    category: "electronics", categoryName: "Electronics",
    price: 185000, originalPrice: 245000,
    rating: 4.8, reviewCount: 2847, stock: 23,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80","https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Industry-leading noise cancellation with 30-hour battery life. Premium sound quality with LDAC support for Hi-Res Audio.",
    specs: { "Driver Size": "30mm", "Battery": "30 hours", "Connectivity": "Bluetooth 5.2", "Weight": "250g", "Noise Cancellation": "Yes" },
    brand: "Sony", tags: ["headphones","wireless","noise-cancelling"],
  },
  {
    id: "p003",
    name: "Samsung 55\" QLED 4K Smart TV",
    category: "electronics", categoryName: "Electronics",
    price: 420000, originalPrice: 580000,
    rating: 4.7, reviewCount: 1923, stock: 15,
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Quantum Dot technology with 100% Color Volume. Alexa and Google Assistant built-in.",
    specs: { "Display": "55\" QLED 4K", "HDR": "HDR10+", "Refresh Rate": "120Hz", "Smart TV": "Tizen OS" },
    brand: "Samsung", tags: ["tv","smart-tv","qled"],
  },
  {
    id: "p005",
    name: "MacBook Pro 14\" M3 Pro",
    category: "electronics", categoryName: "Electronics",
    price: 1450000, originalPrice: 1600000,
    rating: 4.9, reviewCount: 3412, stock: 12,
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80"],
    badge: "new", isNew: true, isBestSeller: false,
    description: "M3 Pro chip delivers exceptional performance for demanding creative workflows.",
    specs: { "Chip": "M3 Pro", "RAM": "18GB", "Storage": "512GB SSD", "Display": "14.2\" Liquid Retina XDR" },
    brand: "Apple", tags: ["laptop","macbook","apple"],
  },
  {
    id: "p010",
    name: "iPad Pro 12.9\" M2 Wi-Fi 256GB",
    category: "electronics", categoryName: "Electronics",
    price: 780000, originalPrice: 850000,
    rating: 4.8, reviewCount: 4108, stock: 19,
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80"],
    badge: "new", isNew: true, isBestSeller: true,
    description: "The most advanced iPad, featuring M2 chip and Liquid Retina XDR display.",
    specs: { "Chip": "M2", "Display": "12.9\" Liquid Retina XDR", "Storage": "256GB", "Camera": "12MP Wide" },
    brand: "Apple", tags: ["ipad","tablet","apple"],
  },
  {
    id: "p012",
    name: "LG C3 65\" OLED evo Smart TV",
    category: "electronics", categoryName: "Electronics",
    price: 890000, originalPrice: 1100000,
    rating: 4.9, reviewCount: 3234, stock: 7,
    images: ["https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Brightest OLED evo ever. Perfect blacks, Dolby Vision & Atmos, 120Hz gaming.",
    specs: { "Panel": "OLED evo", "Size": "65\"", "Resolution": "4K", "Refresh Rate": "120Hz" },
    brand: "LG", tags: ["oled","tv","lg"],
  },
  {
    id: "p013",
    name: "Canon EOS R50 Mirrorless Camera",
    category: "electronics", categoryName: "Electronics",
    price: 395000, originalPrice: 450000,
    rating: 4.7, reviewCount: 892, stock: 14,
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "24.2MP APS-C sensor with DIGIC X image processor. Perfect for content creators.",
    specs: { "Sensor": "24.2MP APS-C", "Video": "4K 30fps", "AF Points": "651", "Weight": "375g" },
    brand: "Canon", tags: ["camera","mirrorless","photography"],
  },
  {
    id: "p014",
    name: "Bose QuietComfort 45 Headphones",
    category: "electronics", categoryName: "Electronics",
    price: 142000, originalPrice: 175000,
    rating: 4.7, reviewCount: 1567, stock: 31,
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Legendary Bose noise cancellation. 24-hour battery. Comfortable over-ear design.",
    specs: { "Battery": "24 hours", "Connectivity": "Bluetooth 5.1", "Noise Cancellation": "Yes", "Weight": "238g" },
    brand: "Bose", tags: ["headphones","wireless","bose"],
  },
  {
    id: "p015",
    name: "HP Pavilion 15 Laptop Intel i7",
    category: "electronics", categoryName: "Electronics",
    price: 485000, originalPrice: 545000,
    rating: 4.5, reviewCount: 743, stock: 22,
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "12th Gen Intel Core i7, 16GB RAM, 512GB SSD. Full HD IPS display for work and entertainment.",
    specs: { "Processor": "Intel i7-1255U", "RAM": "16GB DDR4", "Storage": "512GB NVMe", "Display": "15.6\" FHD IPS" },
    brand: "HP", tags: ["laptop","hp","windows"],
  },
  {
    id: "p016",
    name: "Anker 65W GaN Charger (Nigerian Plug)",
    category: "electronics", categoryName: "Electronics",
    price: 18500, originalPrice: 24000,
    rating: 4.8, reviewCount: 3421, stock: 180,
    images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "Compact 65W GaN charger with Nigerian Type-G plug. Charges laptop + phone simultaneously.",
    specs: { "Wattage": "65W", "Ports": "2x USB-C + 1x USB-A", "Plug": "Type-G (Nigerian)", "Technology": "GaN III" },
    brand: "Anker", tags: ["charger","gan","accessories"],
  },
  {
    id: "p017",
    name: "JBL Flip 6 Portable Speaker",
    category: "electronics", categoryName: "Electronics",
    price: 52000, originalPrice: 65000,
    rating: 4.6, reviewCount: 2103, stock: 45,
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Bold JBL Pro Sound, IP67 waterproof, 12-hour playtime. Perfect for outdoor Nigerian adventures.",
    specs: { "Battery": "12 hours", "Waterproof": "IP67", "Connectivity": "Bluetooth 5.1", "Weight": "550g" },
    brand: "JBL", tags: ["speaker","bluetooth","waterproof"],
  },
  {
    id: "p018",
    name: "Asus ROG Strix G15 Gaming Laptop",
    category: "electronics", categoryName: "Electronics",
    price: 920000, originalPrice: 1050000,
    rating: 4.8, reviewCount: 567, stock: 8,
    images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "AMD Ryzen 9, RTX 3070 Ti, 165Hz display. Built for serious gaming performance.",
    specs: { "CPU": "AMD Ryzen 9 6900HX", "GPU": "RTX 3070 Ti 8GB", "Display": "15.6\" 165Hz", "RAM": "16GB DDR5" },
    brand: "Asus", tags: ["gaming","laptop","asus"],
  },
  {
    id: "p019",
    name: "Xiaomi Smart Band 8 Pro",
    category: "electronics", categoryName: "Electronics",
    price: 28500, originalPrice: 35000,
    rating: 4.5, reviewCount: 1876, stock: 67,
    images: ["https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "AMOLED display, 14-day battery, 150+ workout modes. Health tracking made affordable.",
    specs: { "Display": "1.74\" AMOLED", "Battery": "14 days", "Water Resistance": "5ATM", "GPS": "Built-in" },
    brand: "Xiaomi", tags: ["smartband","fitness","xiaomi"],
  },

  // ── PHONES & ACCESSORIES (10 products) ──────────────────────────────────
  {
    id: "p002",
    name: "Apple iPhone 15 Pro Max",
    category: "phones", categoryName: "Phones",
    price: 899000, originalPrice: 999000,
    rating: 4.9, reviewCount: 5621, stock: 8,
    images: ["https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600&q=80","https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80"],
    badge: "hot", isNew: true, isBestSeller: true,
    description: "A17 Pro chip, titanium design, and the most advanced iPhone camera system ever.",
    specs: { "Chip": "A17 Pro", "Storage": "256GB", "Display": "6.7\" Super Retina XDR", "Camera": "48MP" },
    brand: "Apple", tags: ["iphone","smartphone","apple"],
  },
  {
    id: "p020",
    name: "Samsung Galaxy S24 Ultra",
    category: "phones", categoryName: "Phones",
    price: 750000, originalPrice: 850000,
    rating: 4.8, reviewCount: 3210, stock: 16,
    images: ["https://images.unsplash.com/photo-1610945264803-c22b62831e8b?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "200MP camera, built-in S Pen, Galaxy AI features. The ultimate Android flagship.",
    specs: { "Processor": "Snapdragon 8 Gen 3", "Camera": "200MP", "Battery": "5000mAh", "Display": "6.8\" QHD+ 120Hz" },
    brand: "Samsung", tags: ["samsung","android","flagship"],
  },
  {
    id: "p021",
    name: "Tecno Camon 30 Pro 5G",
    category: "phones", categoryName: "Phones",
    price: 165000, originalPrice: 185000,
    rating: 4.5, reviewCount: 2890, stock: 54,
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80"],
    badge: "hot", isNew: true, isBestSeller: true,
    description: "Nigeria's favourite mid-range phone. 50MP AI camera, 5G ready, 5000mAh battery.",
    specs: { "Processor": "Dimensity 7020", "Camera": "50MP AI", "Battery": "5000mAh 33W", "Display": "6.78\" AMOLED" },
    brand: "Tecno", tags: ["tecno","nigerian","5g"],
  },
  {
    id: "p022",
    name: "Infinix Hot 40 Pro",
    category: "phones", categoryName: "Phones",
    price: 89000, originalPrice: 105000,
    rating: 4.4, reviewCount: 4521, stock: 78,
    images: ["https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "6.78\" FHD+ display, 108MP camera, 5000mAh. Best budget phone in Nigeria right now.",
    specs: { "Processor": "Helio G99", "Camera": "108MP", "Battery": "5000mAh 45W", "RAM": "8GB" },
    brand: "Infinix", tags: ["infinix","budget","nigeria"],
  },
  {
    id: "p023",
    name: "Oraimo FreePods 4 TWS Earbuds",
    category: "phones", categoryName: "Phones",
    price: 12500, originalPrice: 18000,
    rating: 4.3, reviewCount: 8932, stock: 243,
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "Nigeria's #1 selling earbuds. 35h total battery, ENC noise cancellation, IPX5 water resistant.",
    specs: { "Battery": "8h + 27h case", "ANC": "ENC", "Connectivity": "Bluetooth 5.3", "Water Resistance": "IPX5" },
    brand: "Oraimo", tags: ["earbuds","oraimo","nigerian"],
  },
  {
    id: "p024",
    name: "Samsung Galaxy A55 5G",
    category: "phones", categoryName: "Phones",
    price: 210000, originalPrice: 245000,
    rating: 4.6, reviewCount: 1892, stock: 35,
    images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80"],
    badge: "new", isNew: true, isBestSeller: false,
    description: "50MP OIS camera, Exynos 1480, 5000mAh with 25W fast charge. Premium mid-range.",
    specs: { "Processor": "Exynos 1480", "Camera": "50MP OIS", "Battery": "5000mAh 25W", "Display": "6.6\" Super AMOLED" },
    brand: "Samsung", tags: ["samsung","5g","mid-range"],
  },
  {
    id: "p025",
    name: "Baseus 10000mAh Power Bank",
    category: "phones", categoryName: "Phones",
    price: 16500, originalPrice: 22000,
    rating: 4.7, reviewCount: 6234, stock: 189,
    images: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "10000mAh slim powerbank with 20W fast charge. Nepa-proof essential for Nigeria.",
    specs: { "Capacity": "10000mAh", "Output": "20W USB-C PD", "Ports": "2x USB-A + 1x USB-C", "Weight": "228g" },
    brand: "Baseus", tags: ["powerbank","charging","essential"],
  },
  {
    id: "p026",
    name: "Xiaomi Redmi Note 13 Pro+",
    category: "phones", categoryName: "Phones",
    price: 185000, originalPrice: 210000,
    rating: 4.6, reviewCount: 2341, stock: 42,
    images: ["https://images.unsplash.com/photo-1546054454-aa26e2b734c7?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "200MP Leica camera, 120W HyperCharge, Snapdragon 7s Gen 2. Camera king under ₦200K.",
    specs: { "Camera": "200MP Leica", "Charging": "120W HyperCharge", "Processor": "Snapdragon 7s Gen 2", "Display": "6.67\" 1.5K AMOLED" },
    brand: "Xiaomi", tags: ["xiaomi","camera","fast-charge"],
  },
  {
    id: "p027",
    name: "iPhone 15 Clear Case with MagSafe",
    category: "phones", categoryName: "Phones",
    price: 8500, originalPrice: 12000,
    rating: 4.5, reviewCount: 3421, stock: 312,
    images: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Original Apple MagSafe clear case. Protect your iPhone 15 while showing off its design.",
    specs: { "Compatibility": "iPhone 15", "Material": "Polycarbonate", "MagSafe": "Yes", "Protection": "MIL-STD-810G" },
    brand: "Apple", tags: ["case","iphone","magsafe"],
  },
  {
    id: "p028",
    name: "itel P55+ — Budget Champion",
    category: "phones", categoryName: "Phones",
    price: 45000, originalPrice: 52000,
    rating: 4.2, reviewCount: 7823, stock: 134,
    images: ["https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "6000mAh mega battery, 6.6\" HD+ display. The most popular entry-level phone in Nigeria.",
    specs: { "Battery": "6000mAh", "Display": "6.6\" HD+", "Storage": "128GB", "Camera": "13MP AI" },
    brand: "itel", tags: ["itel","budget","nigeria","battery"],
  },

  // ── FASHION (10 products) ────────────────────────────────────────────────
  {
    id: "p004",
    name: "Nike Air Jordan 1 Retro High OG",
    category: "fashion", categoryName: "Fashion",
    price: 95000, originalPrice: 120000,
    rating: 4.9, reviewCount: 8934, stock: 34,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "The iconic Air Jordan 1 in premium leather. A Nigerian streetwear essential.",
    specs: { "Material": "Premium Leather", "Sole": "Air-Sole Unit", "Closure": "Lace-up", "Fit": "True to size" },
    brand: "Nike", tags: ["sneakers","jordan","nike"],
  },
  {
    id: "p009",
    name: "Adidas Ultraboost 23 Running Shoes",
    category: "fashion", categoryName: "Fashion",
    price: 75000, originalPrice: 95000,
    rating: 4.7, reviewCount: 4521, stock: 42,
    images: ["https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "BOOST midsole delivers incredible energy return. PRIMEKNIT upper for a second-skin fit.",
    specs: { "Upper": "Primeknit+", "Midsole": "Boost", "Outsole": "Continental Rubber", "Drop": "10mm" },
    brand: "Adidas", tags: ["shoes","running","adidas"],
  },
  {
    id: "p030",
    name: "Ankara Print Maxi Dress — Lagos Edition",
    category: "fashion", categoryName: "Fashion",
    price: 18500, originalPrice: 25000,
    rating: 4.8, reviewCount: 3421, stock: 87,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4b4ae4?w=600&q=80"],
    badge: "hot", isNew: true, isBestSeller: true,
    description: "Premium 100% cotton Ankara fabric. Vibrant Nigerian print in modern silhouette. Hand-crafted in Lagos.",
    specs: { "Material": "100% Cotton Ankara", "Origin": "Made in Nigeria", "Sizes": "XS–3XL", "Care": "Hand wash cold" },
    brand: "LagosThreads", tags: ["ankara","nigerian","fashion","dress"],
  },
  {
    id: "p031",
    name: "Agbada Set — Premium Aso-Oke",
    category: "fashion", categoryName: "Fashion",
    price: 45000, originalPrice: 60000,
    rating: 4.9, reviewCount: 1876, stock: 23,
    images: ["https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "Traditional Yoruba Agbada in premium hand-woven Aso-Oke. Perfect for owambe, weddings, and celebrations.",
    specs: { "Material": "Aso-Oke weave", "Set Includes": "Buba + Sokoto + Agbada", "Sizes": "S–4XL", "Origin": "Handwoven in Oyo State" },
    brand: "AsoOkeHouse", tags: ["agbada","aso-oke","nigerian","traditional"],
  },
  {
    id: "p032",
    name: "Gucci GG Canvas Tote Bag",
    category: "fashion", categoryName: "Fashion",
    price: 380000, originalPrice: 450000,
    rating: 4.8, reviewCount: 567, stock: 6,
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Authentic Gucci GG Supreme canvas tote. Timeless luxury with the iconic double-G motif.",
    specs: { "Material": "GG Supreme Canvas", "Dimensions": "38×28×14cm", "Hardware": "Gold-tone", "Origin": "Made in Italy" },
    brand: "Gucci", tags: ["gucci","luxury","bag"],
  },
  {
    id: "p033",
    name: "Levi's 501 Original Jeans",
    category: "fashion", categoryName: "Fashion",
    price: 22000, originalPrice: 28000,
    rating: 4.6, reviewCount: 5632, stock: 124,
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "The original straight-leg jean since 1873. Durable denim, iconic fit. A wardrobe staple.",
    specs: { "Material": "100% Cotton Denim", "Fit": "Straight", "Rise": "Regular", "Sizes": "28–42 waist" },
    brand: "Levi's", tags: ["jeans","denim","levis"],
  },
  {
    id: "p034",
    name: "Native Senator Kaftan — Hand-Embroidered",
    category: "fashion", categoryName: "Fashion",
    price: 28000, originalPrice: 38000,
    rating: 4.7, reviewCount: 2341, stock: 45,
    images: ["https://images.unsplash.com/photo-1614093302611-8efc4f5c5623?w=600&q=80"],
    badge: "new", isNew: true, isBestSeller: false,
    description: "Premium cotton senator with intricate hand-embroidery. Ideal for church, office, and owanmbe events.",
    specs: { "Material": "Premium Cotton", "Embroidery": "Hand-done", "Set": "Kaftan + trousers", "Sizes": "S–4XL" },
    brand: "AbujaNatives", tags: ["senator","kaftan","nigerian","native"],
  },
  {
    id: "p035",
    name: "Timberland 6\" Premium Boots",
    category: "fashion", categoryName: "Fashion",
    price: 68000, originalPrice: 82000,
    rating: 4.7, reviewCount: 2109, stock: 29,
    images: ["https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Iconic wheat nubuck leather boots. Waterproof, durable, and stylish for Nigerian roads.",
    specs: { "Material": "Premium Nubuck", "Waterproof": "Yes", "Sole": "Rubber lug", "Sizes": "40–47" },
    brand: "Timberland", tags: ["boots","timberland","footwear"],
  },
  {
    id: "p036",
    name: "Versace Medusa Cologne 100ml",
    category: "fashion", categoryName: "Fashion",
    price: 52000, originalPrice: 68000,
    rating: 4.8, reviewCount: 1432, stock: 38,
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Eros Pour Homme — Fresh, woody, oriental. The signature scent of power and seduction.",
    specs: { "Size": "100ml EDT", "Notes": "Mint, Green Apple, Tonka Bean", "Longevity": "8-10 hours", "Sillage": "Strong" },
    brand: "Versace", tags: ["cologne","perfume","versace"],
  },
  {
    id: "p037",
    name: "Puma RS-X Reinvention Sneakers",
    category: "fashion", categoryName: "Fashion",
    price: 38000, originalPrice: 48000,
    rating: 4.5, reviewCount: 1876, stock: 53,
    images: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "90s running technology reimagined. Chunky RS-X sole with retro colourway.",
    specs: { "Upper": "Mesh + Leather", "Sole": "RS cushioning", "Closure": "Lace-up", "Sizes": "39–46" },
    brand: "Puma", tags: ["sneakers","puma","retro"],
  },

  // ── BEAUTY (10 products) ─────────────────────────────────────────────────
  {
    id: "p006",
    name: "Fenty Beauty Pro Filt'r Foundation",
    category: "beauty", categoryName: "Beauty",
    price: 18500, originalPrice: 22000,
    rating: 4.6, reviewCount: 12043, stock: 89,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "50 inclusive shades. Matte, long-wear formula. The foundation built for every Nigerian skin tone.",
    specs: { "Coverage": "Full", "Finish": "Matte", "SPF": "SPF 15", "Shades": "50" },
    brand: "Fenty Beauty", tags: ["foundation","makeup","fenty"],
  },
  {
    id: "p011",
    name: "Charlotte Tilbury Pillow Talk Lipstick",
    category: "beauty", categoryName: "Beauty",
    price: 12500, originalPrice: 15000,
    rating: 4.9, reviewCount: 18234, stock: 156,
    images: ["https://images.unsplash.com/photo-1586495777744-4e6232bf2d8b?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "The iconic shade that suits every skin tone. Medium coverage, satin finish.",
    specs: { "Finish": "Satin", "Formula": "Long-wear", "Coverage": "Medium", "Cruelty-free": "Yes" },
    brand: "Charlotte Tilbury", tags: ["lipstick","makeup","charlotte"],
  },
  {
    id: "p040",
    name: "Black Opal Fade Milk Even True Complexion",
    category: "beauty", categoryName: "Beauty",
    price: 9500, originalPrice: 13000,
    rating: 4.7, reviewCount: 8921, stock: 234,
    images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "Formulated for melanin-rich skin. Fades dark spots, evens complexion, SPF 15.",
    specs: { "Skin Type": "All types", "Key Ingredient": "Niacinamide + Kojic Acid", "SPF": "15", "Size": "150ml" },
    brand: "Black Opal", tags: ["skincare","darkspot","nigerian","beauty"],
  },
  {
    id: "p041",
    name: "Shea Radiance Moisturizing Lotion",
    category: "beauty", categoryName: "Beauty",
    price: 4800, originalPrice: 6500,
    rating: 4.8, reviewCount: 15432, stock: 432,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "Raw African shea butter lotion. Deeply moisturises, brightens, and protects Nigerian skin.",
    specs: { "Key Ingredient": "Raw Shea Butter", "Skin Type": "All types", "Size": "400ml", "Fragrance": "Light floral" },
    brand: "Shea Radiance", tags: ["lotion","shea","moisturiser","nigerian"],
  },
  {
    id: "p042",
    name: "MAC Studio Fix Powder Plus Foundation",
    category: "beauty", categoryName: "Beauty",
    price: 16000, originalPrice: 19500,
    rating: 4.6, reviewCount: 9234, stock: 67,
    images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "2-in-1 powder + foundation. Matte finish, medium-buildable coverage. Long-wear.",
    specs: { "Coverage": "Medium-Full", "Finish": "Matte", "Shades": "40+", "Size": "15g" },
    brand: "MAC", tags: ["powder","foundation","mac"],
  },
  {
    id: "p043",
    name: "Dyson Airwrap Multi-Styler",
    category: "beauty", categoryName: "Beauty",
    price: 385000, originalPrice: 450000,
    rating: 4.8, reviewCount: 2341, stock: 9,
    images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Style hair with air — no extreme heat damage. Curls, waves, and straight styles in one tool.",
    specs: { "Technology": "Coanda airflow", "Heat": "Max 150°C", "Attachments": "6 included", "Voltage": "220V" },
    brand: "Dyson", tags: ["hair","dyson","styling"],
  },
  {
    id: "p044",
    name: "Maybelline Fit Me Matte Poreless Foundation",
    category: "beauty", categoryName: "Beauty",
    price: 6500, originalPrice: 8500,
    rating: 4.5, reviewCount: 21034, stock: 321,
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "Lightweight formula controls shine all day. Blurs pores for a natural matte finish.",
    specs: { "Coverage": "Light-Medium", "Finish": "Matte", "Skin Type": "Normal-Oily", "Shades": "40" },
    brand: "Maybelline", tags: ["foundation","maybelline","affordable"],
  },
  {
    id: "p045",
    name: "ORS Olive Oil Edge Control",
    category: "beauty", categoryName: "Beauty",
    price: 3500, originalPrice: 4800,
    rating: 4.7, reviewCount: 12341, stock: 567,
    images: ["https://images.unsplash.com/photo-1519415943484-9fa1873496d4?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "The go-to edge control for Nigerian naturals. Smooth, frizz-free hold without flaking.",
    specs: { "Hold": "Maximum", "Key Ingredient": "Olive Oil", "Size": "64g", "Hair Type": "Natural/Relaxed" },
    brand: "ORS", tags: ["edgecontrol","haircare","natural","nigerian"],
  },
  {
    id: "p046",
    name: "Neutrogena Hydro Boost Water Gel",
    category: "beauty", categoryName: "Beauty",
    price: 8200, originalPrice: 11000,
    rating: 4.6, reviewCount: 7832, stock: 145,
    images: ["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Oil-free hyaluronic acid gel. Instantly hydrates and continuously releases moisture.",
    specs: { "Key Ingredient": "Hyaluronic Acid", "Skin Type": "All types", "Size": "50ml", "Oil-Free": "Yes" },
    brand: "Neutrogena", tags: ["moisturiser","neutrogena","skincare"],
  },
  {
    id: "p047",
    name: "Palmer's Cocoa Butter Formula Lotion",
    category: "beauty", categoryName: "Beauty",
    price: 3200, originalPrice: 4200,
    rating: 4.7, reviewCount: 19234, stock: 678,
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "Iconic cocoa butter lotion. Deeply moisturising, eliminates stretch marks, glowing skin.",
    specs: { "Key Ingredient": "Cocoa Butter + Vitamin E", "Size": "400ml", "Skin Type": "Dry/Normal", "Fragrance": "Cocoa" },
    brand: "Palmer's", tags: ["lotion","palmer","cocoa","moisturiser"],
  },

  // ── HOME & KITCHEN (8 products) ──────────────────────────────────────────
  {
    id: "p008",
    name: "Dyson V15 Detect Vacuum Cleaner",
    category: "home-kitchen", categoryName: "Home & Kitchen",
    price: 285000, originalPrice: 340000,
    rating: 4.7, reviewCount: 2156, stock: 28,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Laser detects microscopic dust. Automatically adapts suction power.",
    specs: { "Suction": "240 AW", "Battery": "60 min", "Bin Capacity": "0.77L", "Weight": "3.1kg" },
    brand: "Dyson", tags: ["vacuum","cordless","dyson"],
  },
  {
    id: "p050",
    name: "Scanfrost 15L Microwave Oven",
    category: "home-kitchen", categoryName: "Home & Kitchen",
    price: 38500, originalPrice: 48000,
    rating: 4.6, reviewCount: 3421, stock: 45,
    images: ["https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Nigeria's favourite kitchen brand. 15L capacity, 700W, 5 power levels. Perfect for Nigerian homes.",
    specs: { "Capacity": "15L", "Power": "700W", "Voltage": "220V (Nigerian)", "Timer": "30 min" },
    brand: "Scanfrost", tags: ["microwave","scanfrost","nigerian","kitchen"],
  },
  {
    id: "p051",
    name: "Thermocool 175L Chest Freezer",
    category: "home-kitchen", categoryName: "Home & Kitchen",
    price: 125000, originalPrice: 148000,
    rating: 4.7, reviewCount: 2109, stock: 17,
    images: ["https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Energy-saving chest freezer ideal for Nigerian businesses and homes. Rapid freeze technology.",
    specs: { "Capacity": "175L", "Energy": "A+ rated", "Voltage": "220V", "Warranty": "2 years" },
    brand: "Thermocool", tags: ["freezer","thermocool","nigerian","appliance"],
  },
  {
    id: "p052",
    name: "Sonifer Blender & Smoothie Maker",
    category: "home-kitchen", categoryName: "Home & Kitchen",
    price: 18000, originalPrice: 24000,
    rating: 4.5, reviewCount: 4521, stock: 89,
    images: ["https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "1.5L powerful blender for tomatoes, pepper, smoothies. A Nigerian kitchen essential.",
    specs: { "Capacity": "1.5L", "Power": "1000W", "Speed": "3 settings + pulse", "Blade": "Stainless steel 6-blade" },
    brand: "Sonifer", tags: ["blender","kitchen","nigerian"],
  },
  {
    id: "p053",
    name: "Bruhm 60cm 4-Burner Gas Cooker",
    category: "home-kitchen", categoryName: "Home & Kitchen",
    price: 95000, originalPrice: 118000,
    rating: 4.8, reviewCount: 1876, stock: 22,
    images: ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Stainless steel 4-burner gas cooker with electric oven. Auto-ignition, safety valve.",
    specs: { "Burners": "4 gas", "Oven": "60L electric", "Ignition": "Auto", "Material": "Stainless Steel" },
    brand: "Bruhm", tags: ["gascooker","kitchen","bruhm","nigerian"],
  },
  {
    id: "p054",
    name: "Philips Air Fryer XXL 7.3L",
    category: "home-kitchen", categoryName: "Home & Kitchen",
    price: 145000, originalPrice: 178000,
    rating: 4.7, reviewCount: 1234, stock: 31,
    images: ["https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Fry, bake, grill, and roast with little or no oil. Perfect for suya, chicken, plantain.",
    specs: { "Capacity": "7.3L", "Power": "2225W", "Temperature": "80–200°C", "Presets": "12 cooking presets" },
    brand: "Philips", tags: ["airfryer","philips","cooking"],
  },
  {
    id: "p055",
    name: "3-Piece Non-Stick Cookware Set",
    category: "home-kitchen", categoryName: "Home & Kitchen",
    price: 22000, originalPrice: 30000,
    rating: 4.6, reviewCount: 5432, stock: 76,
    images: ["https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Marble-coated non-stick pots. Gas and electric compatible. Dishwasher safe.",
    specs: { "Set": "3 pots + lids", "Coating": "Marble non-stick", "Compatible": "Gas, Electric, Induction", "Material": "Aluminium" },
    brand: "Vantage", tags: ["cookware","pots","nonstick","kitchen"],
  },
  {
    id: "p056",
    name: "Midea 1.5HP Split Air Conditioner",
    category: "home-kitchen", categoryName: "Home & Kitchen",
    price: 185000, originalPrice: 220000,
    rating: 4.6, reviewCount: 892, stock: 13,
    images: ["https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "1.5HP inverter AC. Energy saving, fast cooling for Nigerian heat. WiFi controlled.",
    specs: { "Capacity": "1.5HP", "Type": "Inverter", "Energy": "A+++", "Feature": "WiFi + Smart control" },
    brand: "Midea", tags: ["ac","airconditioner","midea","cooling"],
  },

  // ── GAMING (8 products) ──────────────────────────────────────────────────
  {
    id: "p007",
    name: "PlayStation 5 Console",
    category: "gaming", categoryName: "Gaming",
    price: 450000, originalPrice: 500000,
    rating: 4.8, reviewCount: 7823, stock: 5,
    images: ["https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "Experience lightning-fast loading with an ultra-high-speed SSD.",
    specs: { "CPU": "AMD Zen 2 8-core", "GPU": "10.3 TFLOPS RDNA 2", "Storage": "825GB SSD", "Resolution": "8K" },
    brand: "Sony", tags: ["gaming","console","ps5"],
  },
  {
    id: "p060",
    name: "Xbox Series X Console",
    category: "gaming", categoryName: "Gaming",
    price: 420000, originalPrice: 470000,
    rating: 4.8, reviewCount: 3421, stock: 7,
    images: ["https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "The fastest, most powerful Xbox ever. 12 teraflops, 4K gaming, 120fps support.",
    specs: { "CPU": "AMD Zen 2 8-core", "GPU": "12 TFLOPS RDNA 2", "Storage": "1TB NVMe SSD", "Resolution": "4K 120fps" },
    brand: "Microsoft", tags: ["xbox","gaming","microsoft"],
  },
  {
    id: "p061",
    name: "Nintendo Switch OLED",
    category: "gaming", categoryName: "Gaming",
    price: 215000, originalPrice: 248000,
    rating: 4.7, reviewCount: 5234, stock: 19,
    images: ["https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Play at home on the TV or on-the-go with the 7\" OLED screen. 64GB storage.",
    specs: { "Display": "7\" OLED", "Storage": "64GB", "Battery": "4.5–9 hours", "Modes": "TV / Tabletop / Handheld" },
    brand: "Nintendo", tags: ["nintendo","switch","portable"],
  },
  {
    id: "p062",
    name: "SteelSeries Apex Pro TKL Keyboard",
    category: "gaming", categoryName: "Gaming",
    price: 85000, originalPrice: 102000,
    rating: 4.8, reviewCount: 1234, stock: 24,
    images: ["https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "World's fastest keyboard with adjustable actuation OmniPoint switches. Per-key RGB.",
    specs: { "Switches": "OmniPoint Adjustable", "RGB": "Per-key RGB", "Layout": "Tenkeyless", "Response": "0.7ms" },
    brand: "SteelSeries", tags: ["keyboard","gaming","rgb"],
  },
  {
    id: "p063",
    name: "Logitech G Pro X Superlight Mouse",
    category: "gaming", categoryName: "Gaming",
    price: 48000, originalPrice: 58000,
    rating: 4.9, reviewCount: 2341, stock: 36,
    images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Only 61 grams. HERO 25K sensor. The mouse used by pro esports players worldwide.",
    specs: { "Weight": "61g", "Sensor": "HERO 25K DPI", "Buttons": "5", "Battery": "70 hours" },
    brand: "Logitech", tags: ["mouse","gaming","logitech"],
  },
  {
    id: "p064",
    name: "Razer BlackShark V2 Gaming Headset",
    category: "gaming", categoryName: "Gaming",
    price: 42000, originalPrice: 52000,
    rating: 4.7, reviewCount: 1876, stock: 41,
    images: ["https://images.unsplash.com/photo-1599669454699-248893623440?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "THX 7.1 Spatial Audio, TriForce Titanium 50mm drivers. Crystal clear comms.",
    specs: { "Drivers": "TriForce 50mm", "Audio": "THX 7.1 Spatial", "Microphone": "Cardioid", "Connection": "USB + 3.5mm" },
    brand: "Razer", tags: ["headset","gaming","razer"],
  },
  {
    id: "p065",
    name: "PS5 DualSense Wireless Controller",
    category: "gaming", categoryName: "Gaming",
    price: 55000, originalPrice: 65000,
    rating: 4.8, reviewCount: 4321, stock: 28,
    images: ["https://images.unsplash.com/photo-1617096200347-cb04ae810b1d?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Haptic feedback and adaptive triggers bring immersive gaming to life.",
    specs: { "Battery": "12 hours", "Haptics": "Advanced haptic feedback", "Triggers": "Adaptive", "Charging": "USB-C" },
    brand: "Sony", tags: ["controller","ps5","gaming"],
  },
  {
    id: "p066",
    name: "BenQ MOBIUZ 27\" 165Hz Gaming Monitor",
    category: "gaming", categoryName: "Gaming",
    price: 195000, originalPrice: 235000,
    rating: 4.7, reviewCount: 876, stock: 14,
    images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "1ms IPS, 165Hz, HDRi — built for competitive gaming. Eye-Care certified.",
    specs: { "Size": "27\"", "Panel": "IPS", "Refresh": "165Hz", "Response": "1ms GTG" },
    brand: "BenQ", tags: ["monitor","gaming","benq"],
  },

  // ── SPORTS & FITNESS (8 products) ────────────────────────────────────────
  {
    id: "p070",
    name: "Adidas Predator Elite FG Football Boots",
    category: "sports", categoryName: "Sports & Fitness",
    price: 78000, originalPrice: 96000,
    rating: 4.8, reviewCount: 3421, stock: 27,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "Zone Skin upper for superior control. CONTROLFRAME outsole. The boot of champions.",
    specs: { "Upper": "Zone Skin", "Outsole": "CONTROLFRAME", "Ground": "Firm Ground", "Sizes": "39–47" },
    brand: "Adidas", tags: ["football","boots","adidas","sport"],
  },
  {
    id: "p071",
    name: "Fitness Dumbbell Set 20kg Adjustable",
    category: "sports", categoryName: "Sports & Fitness",
    price: 45000, originalPrice: 58000,
    rating: 4.7, reviewCount: 2109, stock: 34,
    images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Adjustable dumbbells from 2–20kg. Replace 6 pairs of dumbbells. Home gym essential.",
    specs: { "Weight Range": "2–20kg", "Adjustment": "Quick-release", "Material": "Cast Iron", "Grip": "Knurled chrome" },
    brand: "PowerMax", tags: ["dumbbell","fitness","gym","weights"],
  },
  {
    id: "p072",
    name: "Nike Dri-FIT Running Set",
    category: "sports", categoryName: "Sports & Fitness",
    price: 28500, originalPrice: 36000,
    rating: 4.6, reviewCount: 1876, stock: 65,
    images: ["https://images.unsplash.com/photo-1556742044-3c52d6e88c62?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Moisture-wicking Dri-FIT fabric. Shorts + top set designed for Nigerian heat.",
    specs: { "Material": "Dri-FIT polyester", "Set": "Top + shorts", "Fit": "Standard", "Sizes": "S–3XL" },
    brand: "Nike", tags: ["running","nike","sportswear"],
  },
  {
    id: "p073",
    name: "Kipsta Size 5 Football (NPLF Match Ball)",
    category: "sports", categoryName: "Sports & Fitness",
    price: 8500, originalPrice: 12000,
    rating: 4.8, reviewCount: 8923, stock: 234,
    images: ["https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "NPLF-approved match football. 32-panel thermally bonded. Used in Nigerian leagues.",
    specs: { "Size": "5 (Official)", "Panel": "32-panel", "Bladder": "Butyl", "Certification": "FIFA Basic" },
    brand: "Kipsta", tags: ["football","soccer","ball","sport"],
  },
  {
    id: "p074",
    name: "Garmin Forerunner 255 GPS Watch",
    category: "sports", categoryName: "Sports & Fitness",
    price: 185000, originalPrice: 220000,
    rating: 4.8, reviewCount: 1234, stock: 16,
    images: ["https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Advanced running dynamics, HRV status, race predictor. Built for serious Nigerian runners.",
    specs: { "GPS": "Multi-band GPS", "Battery": "14 days smartwatch / 30h GPS", "Heart Rate": "Optical wrist HR", "Display": "1.3\" MIP" },
    brand: "Garmin", tags: ["garmin","gps","running","watch"],
  },
  {
    id: "p075",
    name: "Yoga Mat Premium 6mm Non-Slip",
    category: "sports", categoryName: "Sports & Fitness",
    price: 12000, originalPrice: 16500,
    rating: 4.7, reviewCount: 3421, stock: 112,
    images: ["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "6mm TPE eco-friendly yoga mat. Non-slip, sweat-resistant. Perfect for home workouts.",
    specs: { "Thickness": "6mm", "Material": "TPE Eco", "Dimensions": "183×61cm", "Weight": "1.1kg" },
    brand: "PROfit", tags: ["yoga","mat","fitness","home"],
  },
  {
    id: "p076",
    name: "Wilson Clash 100 Tennis Racket",
    category: "sports", categoryName: "Sports & Fitness",
    price: 68000, originalPrice: 82000,
    rating: 4.7, reviewCount: 567, stock: 19,
    images: ["https://images.unsplash.com/photo-1617083934555-ac7e7eddb1f8?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Carbon Mapping technology for ultimate flexibility + stability. Great for all levels.",
    specs: { "Head Size": "100 sq in", "Weight": "295g", "String Pattern": "16×19", "Grip": "4 3/8" },
    brand: "Wilson", tags: ["tennis","wilson","racket"],
  },
  {
    id: "p077",
    name: "Resistance Bands Set (5 Levels)",
    category: "sports", categoryName: "Sports & Fitness",
    price: 7500, originalPrice: 11000,
    rating: 4.8, reviewCount: 6234, stock: 345,
    images: ["https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "5-level resistance bands for home workouts. Glutes, legs, arms — full body training.",
    specs: { "Levels": "5 resistance levels", "Material": "Natural latex", "Weight Range": "10–50 lbs", "Includes": "Carry bag" },
    brand: "FitLoop", tags: ["resistance","bands","fitness","home"],
  },

  // ── BOOKS & MEDIA (8 products) ───────────────────────────────────────────
  {
    id: "p080",
    name: "Things Fall Apart — Chinua Achebe",
    category: "books", categoryName: "Books & Media",
    price: 3500, originalPrice: 4500,
    rating: 4.9, reviewCount: 24321, stock: 345,
    images: ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "Africa's most read novel. The timeless story of Okonkwo and the Igbo people. Every Nigerian must read.",
    specs: { "Author": "Chinua Achebe", "Pages": "209", "Publisher": "Heinemann", "Language": "English" },
    brand: "Heinemann", tags: ["achebe","african","classic","novel"],
  },
  {
    id: "p081",
    name: "Rich Dad Poor Dad — Robert Kiyosaki",
    category: "books", categoryName: "Books & Media",
    price: 4200, originalPrice: 5800,
    rating: 4.7, reviewCount: 18234, stock: 234,
    images: ["https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "#1 personal finance book of all time. Build wealth, think like the rich. Essential for every Nigerian entrepreneur.",
    specs: { "Author": "Robert Kiyosaki", "Pages": "336", "Publisher": "Warner Books", "Category": "Finance/Self-help" },
    brand: "Warner Books", tags: ["finance","business","kiyosaki","entrepreneurship"],
  },
  {
    id: "p082",
    name: "Half of a Yellow Sun — Chimamanda Adichie",
    category: "books", categoryName: "Books & Media",
    price: 4800, originalPrice: 6200,
    rating: 4.9, reviewCount: 8934, stock: 189,
    images: ["https://images.unsplash.com/photo-1535398089889-dd807df1dfaa?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "The Orange Prize-winning novel about love and war during the Biafra conflict. Chimamanda at her finest.",
    specs: { "Author": "Chimamanda Ngozi Adichie", "Pages": "433", "Award": "Orange Prize for Fiction", "Genre": "Historical Fiction" },
    brand: "Farafina", tags: ["adichie","nigerian","biafra","novel"],
  },
  {
    id: "p083",
    name: "The Psychology of Money — Morgan Housel",
    category: "books", categoryName: "Books & Media",
    price: 5200, originalPrice: 7000,
    rating: 4.8, reviewCount: 12341, stock: 178,
    images: ["https://images.unsplash.com/photo-1601628828688-632f38a5a7d0?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: true,
    description: "19 timeless lessons on wealth, greed, and happiness. The best modern personal finance read.",
    specs: { "Author": "Morgan Housel", "Pages": "256", "Publisher": "Harriman House", "Category": "Finance/Psychology" },
    brand: "Harriman House", tags: ["finance","money","psychology","investment"],
  },
  {
    id: "p084",
    name: "Atomic Habits — James Clear",
    category: "books", categoryName: "Books & Media",
    price: 5500, originalPrice: 7200,
    rating: 4.9, reviewCount: 21034, stock: 234,
    images: ["https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&q=80"],
    badge: "hot", isNew: false, isBestSeller: true,
    description: "The proven system to build good habits. #1 bestseller in 35 countries. Life-changing for Nigerian professionals.",
    specs: { "Author": "James Clear", "Pages": "319", "Publisher": "Avery", "Category": "Self-improvement" },
    brand: "Avery Publishing", tags: ["habits","selfhelp","productivity","james-clear"],
  },
  {
    id: "p085",
    name: "Kindle Paperwhite 11th Gen",
    category: "books", categoryName: "Books & Media",
    price: 68000, originalPrice: 80000,
    rating: 4.8, reviewCount: 4321, stock: 43,
    images: ["https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "6.8\" display, adjustable warm light, waterproof, 10 weeks battery. Carry 1000 books.",
    specs: { "Display": "6.8\" 300ppi", "Storage": "8GB", "Battery": "Up to 10 weeks", "Waterproof": "IPX8" },
    brand: "Amazon", tags: ["kindle","ereader","amazon","books"],
  },
  {
    id: "p086",
    name: "Purple Hibiscus — Chimamanda Adichie",
    category: "books", categoryName: "Books & Media",
    price: 3800, originalPrice: 5000,
    rating: 4.8, reviewCount: 6234, stock: 145,
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80"],
    badge: "sale", isNew: false, isBestSeller: false,
    description: "Adichie's debut novel. A story of a Nigerian family under political and religious repression.",
    specs: { "Author": "Chimamanda Ngozi Adichie", "Pages": "307", "Award": "Commonwealth Writers' Prize", "Genre": "Literary Fiction" },
    brand: "Farafina", tags: ["adichie","nigerian","debut","novel"],
  },
  {
    id: "p087",
    name: "How to Build a Successful Business in Nigeria",
    category: "books", categoryName: "Books & Media",
    price: 4500, originalPrice: 6000,
    rating: 4.7, reviewCount: 3421, stock: 167,
    images: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80"],
    badge: "new", isNew: true, isBestSeller: false,
    description: "Practical guide to entrepreneurship in Nigeria. Funding, registration, taxes, and growth strategies.",
    specs: { "Author": "Dr. Taiwo Adesanya", "Pages": "312", "Publisher": "Lagos Business Press", "Edition": "2024 Updated" },
    brand: "Lagos Business Press", tags: ["business","nigeria","entrepreneurship","startup"],
  },
];

// ─── Derived exports ──────────────────────────────────────────────────────────
export const FLASH_SALES   = PRODUCTS.filter((p) => p.badge === "sale").slice(0, 6);
export const BEST_SELLERS  = PRODUCTS.filter((p) => p.isBestSeller).slice(0, 8);
export const NEW_ARRIVALS  = PRODUCTS.filter((p) => p.isNew).slice(0, 8);

export const BRANDS = [
  { id: "apple",    name: "Apple",           logo: "🍎" },
  { id: "samsung",  name: "Samsung",         logo: "📱" },
  { id: "sony",     name: "Sony",            logo: "🎵" },
  { id: "nike",     name: "Nike",            logo: "✓"  },
  { id: "tecno",    name: "Tecno",           logo: "📲" },
  { id: "oraimo",   name: "Oraimo",          logo: "🎧" },
  { id: "dyson",    name: "Dyson",           logo: "💨" },
  { id: "scanfrost",name: "Scanfrost",       logo: "🏠" },
  { id: "lg",       name: "LG",              logo: "📺" },
  { id: "fenty",    name: "Fenty Beauty",    logo: "💄" },
  { id: "infinix",  name: "Infinix",         logo: "📱" },
  { id: "itel",     name: "itel",            logo: "📟" },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Adaeze Okafor",
    location: "Lagos, Nigeria",
    rating: 5,
    comment: "NexMart has completely changed how I shop. The product quality is exceptional and delivery was faster than expected. Highly recommend!",
    avatar: "AO",
    verified: true,
    date: "2 days ago",
    product: "Fenty Beauty Foundation",
  },
  {
    id: 2,
    name: "Emeka Nwosu",
    location: "Abuja, Nigeria",
    rating: 5,
    comment: "Best online marketplace in Nigeria. Got my MacBook Pro delivered in 2 days. The packaging was perfect and everything was 100% authentic.",
    avatar: "EN",
    verified: true,
    date: "1 week ago",
    product: "MacBook Pro M3",
  },
  {
    id: 3,
    name: "Fatima Al-Hassan",
    location: "Kano, Nigeria",
    rating: 5,
    comment: "The return process was seamless when I needed to exchange a size. Customer support was extremely helpful and very responsive.",
    avatar: "FA",
    verified: true,
    date: "2 weeks ago",
    product: "Ankara Maxi Dress",
  },
  {
    id: 4,
    name: "Chukwudi Eze",
    location: "Port Harcourt",
    rating: 4,
    comment: "Great selection of electronics. Prices are competitive and the flash sales are amazing. Found the PS5 at the best price in Nigeria!",
    avatar: "CE",
    verified: true,
    date: "3 weeks ago",
    product: "PlayStation 5",
  },
  {
    id: 5,
    name: "Blessing Okonkwo",
    location: "Enugu, Nigeria",
    rating: 5,
    comment: "I've been shopping on NexMart for 6 months. Every single order has been perfect. The quality checks are real. No fakes here!",
    avatar: "BO",
    verified: true,
    date: "1 month ago",
    product: "iPhone 15 Pro Max",
  },
  {
    id: 6,
    name: "Yusuf Musa",
    location: "Kaduna, Nigeria",
    rating: 5,
    comment: "Ordered PS5 during the flash sale — saved ₦50,000. Delivered in 48 hours. This is the future of Nigerian e-commerce, no doubt.",
    avatar: "YM",
    verified: true,
    date: "1 month ago",
    product: "PlayStation 5",
  },
];