// Mock data — used when server is not connected
// When server is connected, API calls replace these

export const CATEGORIES = [
  { id: "electronics", name: "Electronics", icon: "📱", count: 1240, color: "#3B82F6" },
  { id: "fashion", name: "Fashion", icon: "👗", count: 890, color: "#EC4899" },
  { id: "beauty", name: "Beauty", icon: "💄", count: 560, color: "#F59E0B" },
  { id: "home-kitchen", name: "Home & Kitchen", icon: "🏠", count: 720, color: "#10B981" },
  { id: "gaming", name: "Gaming", icon: "🎮", count: 430, color: "#8B5CF6" },
  { id: "phones", name: "Phones & Accessories", icon: "📲", count: 980, color: "#EF4444" },
  { id: "sports", name: "Sports & Fitness", icon: "💪", count: 340, color: "#F97316" },
  { id: "books", name: "Books & Media", icon: "📚", count: 230, color: "#6366F1" },
];

export const PRODUCTS = [
  {
    id: "p001",
    name: "Sony WH-1000XM5 Wireless Headphones",
    category: "electronics",
    categoryName: "Electronics",
    price: 185000,
    originalPrice: 245000,
    rating: 4.8,
    reviewCount: 2847,
    stock: 23,
    images: [
      "https://images.unsplash.com/photo-1583305727488-61f82c7eae4b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1721300217761-e580569047f5?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fFNvbnklMjBXSC0xMDAwWE01JTIwV2lyZWxlc3MlMjBIZWFkcGhvbmVzfGVufDB8fDB8fHww",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: true,
    description: "Industry-leading noise cancellation with 30-hour battery life. Premium sound quality with LDAC support.",
    specs: { "Driver Size": "30mm", "Battery": "30 hours", "Connectivity": "Bluetooth 5.2", "Weight": "250g" },
    brand: "Sony",
    tags: ["headphones", "wireless", "noise-cancelling"],
  },
  {
    id: "p002",
    name: "Apple iPhone 15 Pro Max",
    category: "phones",
    categoryName: "Phones",
    price: 899000,
    originalPrice: 999000,
    rating: 4.9,
    reviewCount: 5621,
    stock: 8,
    images: [
      "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80",
    ],
    badge: "hot",
    isNew: true,
    isBestSeller: true,
    description: "A17 Pro chip, titanium design, and the most advanced iPhone camera system ever.",
    specs: { "Chip": "A17 Pro", "Storage": "256GB", "Display": "6.7\" Super Retina XDR", "Camera": "48MP" },
    brand: "Apple",
    tags: ["iphone", "smartphone", "apple"],
  },
  {
    id: "p003",
    name: "Samsung 55\" QLED 4K Smart TV",
    category: "electronics",
    categoryName: "Electronics",
    price: 420000,
    originalPrice: 580000,
    rating: 4.7,
    reviewCount: 1923,
    stock: 15,
    images: [
      "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/63/4819814/1.jpg?3967",
      "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/63/4819814/3.jpg?3967",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: true,
    description: "Quantum Dot technology with 100% Color Volume. Alexa and Google Assistant built-in.",
    specs: { "Display": "55\" QLED 4K", "HDR": "HDR10+", "Refresh Rate": "120Hz", "Smart TV": "Tizen OS" },
    brand: "Samsung",
    tags: ["tv", "smart-tv", "qled"],
  },
  {
    id: "p004",
    name: "Nike Air Jordan 1 Retro High OG",
    category: "fashion",
    categoryName: "Fashion",
    price: 95000,
    originalPrice: 120000,
    rating: 4.9,
    reviewCount: 8934,
    stock: 34,
    images: [
      "https://www.snipesusa.com/dw/image/v2/BFKF_PRD/on/demandware.static/-/Sites-snipes-master-catalog/default/dwd93e08e7/images/hi-res/jordan_fd2596-101_01.jpg?sw=1600&sh=2008",
      "https://www.snipesusa.com/dw/image/v2/BFKF_PRD/on/demandware.static/-/Sites-snipes-master-catalog/default/dw630afd67/images/hi-res/jordan_fd2596-602_01.jpg?sw=1600&sh=2008",
      "https://www.snipesusa.com/dw/image/v2/BFKF_PRD/on/demandware.static/-/Sites-snipes-master-catalog/default/dw9a194be4/images/hi-res/jordan_fd2596-200_01.jpg?sw=1600&sh=2008",
    ],
    badge: "hot",
    isNew: false,
    isBestSeller: true,
    description: "The iconic Air Jordan 1 in premium leather with original colorway.",
    specs: { "Material": "Premium Leather", "Sole": "Air-Sole Unit", "Closure": "Lace-up", "Fit": "True to size" },
    brand: "Nike",
    tags: ["sneakers", "jordan", "nike"],
  },
  {
    id: "p005",
    name: "MacBook Pro 14\" M3 Pro",
    category: "electronics",
    categoryName: "Electronics",
    price: 1450000,
    originalPrice: 1600000,
    rating: 4.9,
    reviewCount: 3412,
    stock: 12,
    images: [
      "http://applepremiumstore.com.ng/wp-content/uploads/2024/06/mbp-14-digitalmat-gallery-1-202310.png",
      "https://www.techadvisor.com/wp-content/uploads/2023/11/Macbook-Pro-14-M3-2.jpg?resize=1024%2C768&quality=50&strip=all",
    ],
    badge: "new",
    isNew: true,
    isBestSeller: false,
    description: "M3 Pro chip delivers exceptional performance for demanding workflows.",
    specs: { "Chip": "M3 Pro", "RAM": "18GB", "Storage": "512GB SSD", "Display": "14.2\" Liquid Retina XDR" },
    brand: "Apple",
    tags: ["laptop", "macbook", "apple"],
  },
  {
    id: "p006",
    name: "Fenty Beauty Pro Filt'r Foundation",
    category: "beauty",
    categoryName: "Beauty",
    price: 18500,
    originalPrice: 22000,
    rating: 4.6,
    reviewCount: 12043,
    stock: 89,
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80",
      "https://fentybeauty.com/cdn/shop/products/FB31006_FB0400_alt1.jpg?format=webp&v=1762198540&width=800",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: true,
    description: "Full-coverage, matte foundation in 50 shades. Long-wear formula.",
    specs: { "Coverage": "Full", "Finish": "Matte", "SPF": "SPF 15", "Shades": "50 shades" },
    brand: "Fenty Beauty",
    tags: ["foundation", "makeup", "beauty"],
  },
  {
    id: "p007",
    name: "PlayStation 5 Console",
    category: "gaming",
    categoryName: "Gaming",
    price: 450000,
    originalPrice: 500000,
    rating: 4.8,
    reviewCount: 7823,
    stock: 5,
    images: [
      "https://i5.walmartimages.com/seo/New-Sony-Playstation-5-Disc-Version-Video-Game-PS-5-Console_d84054ce-8d3a-4993-936c-5b32e6e64f01.5a53ae755ac7ea3b5cb25b33d6cb1a8e.jpeg",
      "https://i5.walmartimages.com/asr/7311323d-bd39-423a-b6fc-ff56a1e04322.ed6a5804b50192ac6617559f43139d6e.png",
      "https://i5.walmartimages.com/asr/1d3977ca-d04f-4601-afcd-c5286ec75904.0f801b2bb350f6c273755982d5896706.png",
    ],
    badge: "hot",
    isNew: false,
    isBestSeller: true,
    description: "Experience lightning-fast loading with an ultra-high-speed SSD.",
    specs: { "CPU": "AMD Zen 2 8-core", "GPU": "10.3 TFLOPS RDNA 2", "Storage": "825GB SSD", "Resolution": "8K" },
    brand: "Sony",
    tags: ["gaming", "console", "ps5"],
  },
  {
    id: "p008",
    name: "Dyson V15 Detect Vacuum Cleaner",
    category: "home-kitchen",
    categoryName: "Home & Kitchen",
    price: 285000,
    originalPrice: 340000,
    rating: 4.7,
    reviewCount: 2156,
    stock: 28,
    images: [
      "https://i5.walmartimages.com/seo/Dyson-V15-Detect-Vacuum-Yellow-Nickel-Previous-Gen_c6cc9370-fbc0-4a17-ae79-67dd675b8eea.b5bd41a7cf755840c8d92ef7377beeba.jpeg",
      "https://i5.walmartimages.com/asr/024bfd45-4d5d-4830-b834-8263666c8a20.99b10131898b95297bd233f87865d547.jpeg",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: false,
    description: "Laser detects microscopic dust. Automatically adapts suction power.",
    specs: { "Suction": "240 AW", "Battery": "60 min", "Bin Capacity": "0.77L", "Weight": "3.1kg" },
    brand: "Dyson",
    tags: ["vacuum", "cordless", "dyson"],
  },
  {
    id: "p009",
    name: "Adidas Ultraboost 23 Running Shoes",
    category: "fashion",
    categoryName: "Fashion",
    price: 75000,
    originalPrice: 95000,
    rating: 4.7,
    reviewCount: 4521,
    stock: 42,
    images: [
      "https://media.6media.me/media/catalog/product/h/q/hq6351_1_footwear_photography_sidelateralcenterview_white.jpg",
      "https://media.6media.me/media/catalog/product/h/q/hq6351_14_footwear_photography_heromrktngview2_white.jpg",
      "https://media.6media.me/media/catalog/product/h/q/hq6351_9_footwear_photography_detailview2_white.jpg",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: false,
    description: "BOOST midsole delivers incredible energy return. PRIMEKNIT upper for a second-skin fit.",
    specs: { "Upper": "Primeknit+", "Midsole": "Boost", "Outsole": "Continental Rubber", "Drop": "10mm" },
    brand: "Adidas",
    tags: ["shoes", "running", "adidas"],
  },
  {
    id: "p010",
    name: "iPad Pro 12.9\" M2 Wi-Fi 256GB",
    category: "electronics",
    categoryName: "Electronics",
    price: 780000,
    originalPrice: 850000,
    rating: 4.8,
    reviewCount: 4108,
    stock: 19,
    images: [
      "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/79/7852914/1.jpg?0558",
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80",
    ],
    badge: "new",
    isNew: true,
    isBestSeller: true,
    description: "The most advanced iPad, featuring M2 chip and Liquid Retina XDR display.",
    specs: { "Chip": "M2", "Display": "12.9\" Liquid Retina XDR", "Storage": "256GB", "Camera": "12MP Wide" },
    brand: "Apple",
    tags: ["ipad", "tablet", "apple"],
  },
  {
    id: "p011",
    name: "Charlotte Tilbury Pillow Talk Lipstick",
    category: "beauty",
    categoryName: "Beauty",
    price: 12500,
    originalPrice: 15000,
    rating: 4.9,
    reviewCount: 18234,
    stock: 156,
    images: [
      "https://images.unsplash.com/photo-1626895872564-b691b6877b83?q=80&w=764",
      "https://images.unsplash.com/photo-1610166970010-c2e6c3da7164?q=80&w=764",
    ],
    badge: "hot",
    isNew: false,
    isBestSeller: true,
    description: "The iconic Pillow Talk lipstick. Medium-coverage, satin-finish nude pink.",
    specs: { "Finish": "Satin", "Formula": "Long-wear", "Coverage": "Medium", "Cruelty-free": "Yes" },
    brand: "Charlotte Tilbury",
    tags: ["lipstick", "makeup", "beauty"],
  },
  {
    id: "p012",
    name: "LG C3 65\" OLED evo Smart TV",
    category: "electronics",
    categoryName: "Electronics",
    price: 890000,
    originalPrice: 1100000,
    rating: 4.9,
    reviewCount: 3234,
    stock: 7,
    images: [
      "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&q=80",
    ],
    badge: "sale",
    isNew: false,
    isBestSeller: true,
    description: "Brightest OLED evo ever. Perfect blacks, Dolby Vision & Atmos, 120Hz gaming.",
    specs: { "Panel": "OLED evo", "Size": "65\"", "Resolution": "4K", "Refresh Rate": "120Hz" },
    brand: "LG",
    tags: ["oled", "tv", "lg"],
  },
];

export const FLASH_SALES = PRODUCTS.filter((p) => p.badge === "sale").slice(0, 6);
export const BEST_SELLERS = PRODUCTS.filter((p) => p.isBestSeller).slice(0, 8);
export const NEW_ARRIVALS = PRODUCTS.filter((p) => p.isNew).slice(0, 8);

export const BRANDS = [
  { id: "apple", name: "Apple", logo: "🍎" },
  { id: "samsung", name: "Samsung", logo: "📱" },
  { id: "sony", name: "Sony", logo: "🎵" },
  { id: "nike", name: "Nike", logo: "✓" },
  { id: "adidas", name: "Adidas", logo: "⭐" },
  { id: "dyson", name: "Dyson", logo: "💨" },
  { id: "lg", name: "LG", logo: "📺" },
  { id: "fenty", name: "Fenty Beauty", logo: "💄" },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Adaeze Okafor",
    location: "Lagos, Nigeria",
    rating: 5,
    comment: "NexMart has completely changed how I shop. The product quality is exceptional and delivery was faster than expected. Highly recommend!",
    avatar: "AO",
    verified: true,
    date: "2 days ago",
  },
  {
    id: 2,
    name: "Emeka Nwosu",
    location: "Abuja, Nigeria",
    rating: 5,
    comment: "Best online marketplace in Nigeria. Got my MacBook Pro delivered in 2 days. The packaging was perfect and everything was authentic.",
    avatar: "EN",
    verified: true,
    date: "1 week ago",
  },
  {
    id: 3,
    name: "Fatima Al-Hassan",
    location: "Kano, Nigeria",
    rating: 5,
    comment: "The return process was seamless when I needed to exchange a size. Customer support was extremely helpful and responsive.",
    avatar: "FA",
    verified: true,
    date: "2 weeks ago",
  },
  {
    id: 4,
    name: "Chukwudi Eze",
    location: "Port Harcourt",
    rating: 4,
    comment: "Great selection of electronics. Prices are competitive and the flash sales are amazing. Found the PS5 at a great price!",
    avatar: "CE",
    verified: true,
    date: "3 weeks ago",
  },
];